In [1]:
import numpy
n=numpy.arange(27)

In [2]:
type(n)

numpy.ndarray

In [3]:
#This is a 1 dimensional array
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [4]:
#Make into 2D array
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [5]:
#Make into 3D array
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [15]:
#convert a list to a numpy array
m=numpy.asarray([[123,12,123,12],[],[12,3]])
type(m)

numpy.ndarray

In [16]:
print(m)

[list([123, 12, 123, 12]) list([]) list([12, 3])]


In [17]:
#IMAGE PROCESSING W/ NUMPY AND OPENCV
import cv2

In [18]:
#Print the array in greyscale
im_g=cv2.imread("smallgreyimage.png",0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [19]:
#Print the array in RGB scale (aka. Red layer, Green layer, and Blue layer)
im_rgb=cv2.imread("smallgreyimage.png",1)
im_rgb

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [20]:
#How to create images out of a numpy reading (new file created in directory)
cv2.imwrite("newsmallgreyimage.png", im_g)

True

In [21]:
im_g[0:2] #first 2 rows

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [22]:
im_g[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [24]:
im_g.shape

(3, 5)

In [25]:
#Iterate through rows
for i in im_g:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [26]:
#Iterate through columns (use transpose)
for i in im_g.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [27]:
#Iterate through individual values
for i in im_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [40]:
#How to concatenate 2 arrays
imconc=numpy.hstack((im_g,im_g)) #Stands for horizontal stack
print(imconc)

[[187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182]]


In [41]:
#How to split an array
imsplit=numpy.vsplit(im_g,3) #Stands for vertical split
imsplit

[array([[187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182]], dtype=uint8)]

In [42]:
imsplit[0] #Shows the first array

array([[187, 158, 104, 121, 143]], dtype=uint8)